// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Logf(arg1, arg2) {
  return window['go']['main']['App']['Logf'](arg1, arg2);
}

export function RunBindingProcess() {
  return window['go']['main']['App']['RunBindingProcess']();
}
